openapi: 3.0.3
info:
  title: User API
  description: User API
  version: 1.0.0
servers:
  - url: 'http://localhost:8080'
paths:
  /api/v1/user:
    get:
      summary: method for find user
      operationId: findUsers
      parameters:
        - in: query
          name: userParams
          allowEmptyValue: true
          schema:
            $ref: '#/components/schemas/FindUserRequest'
      responses:
        200:
          description: found users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserResponse'

components:
  schemas:
    FindUserRequest:
      type: object
      description: user Request parameters
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        phone:
          type: string
    UserResponse:
      type: object
      description: User response DTO
      properties:
        name:
          type: string
        phone:
          type: string